#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Carl Sverre"
email = "82591+carlsverre@users.noreply.github.com"

[ui]
default-command = "log"
merge-editor = "meld"
diff-editor = "meld"

[revsets]
log = "present(@) | ancestors(immutable_heads()::, 2) | present(trunk())"

[revset-aliases]
'user()' = 'user(*carl*sverre*)'
'user(x)' = 'author(x) | committer(x)'
'unpushed' = "remote_bookmarks()::"
'local' = "(remote_bookmarks()..@)::"
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
local = ["log", "-r", "local"]
